- hosts: localhost
  vars_files:
      - files_list.yml
  tasks: 
    - name: checksum matching 
      stat:
        path: "{{ item.name }}" 
      with_items: "{{ files }}"
      register: test
    - debug:
        msg: "checksum matched"
      when: '"{{ item.item.checksum }}" == "{{ item.stat.checksum }}"'
      loop: "{{ test.results }}"
    - debug:
        msg: "checksum not matched"
      when: '"{{ item.item.checksum }}" != "{{ item.stat.checksum }}"'
      loop: "{{ test.results }}"

  
